from Bio.SeqUtils import MeltingTemp as mt
from Bio.SeqUtils import Seq
from Bio.SeqUtils import GC

sequencia='''AGTAAATCCTGTGTGCTAATTGAGGTGCATTGGTCTGCAAATCGAGTTGCTAGGCAATAAACACATTTGG
ATTAATTTTAATCGTTCGTTGAGCGATTAGCAGAGAACTGACCAGAACATGTCTGGTCGTAAAGCTCAGG
GAAAAACCCTGGGCGTCAATATGGTACGACGAGGAGTTCGCTCCTTGTCAAACAAAATAAAACAAAAAAC
AAAACAAATTGGAAACAGACCTGGACCTTCAAGAGGTGTTCAAGGATTTATCTTTTTCTTTTTGTTCAAC
ATTTTGACTGGAAAAAAGATCACAGCCCACCTAAAGAGGTTGTGGAAAATGCTGGACCCAAGACAAGGCT'''


#CALCULA A PROPORÇÃO GC
print("A proporção GC é : ",  GC(sequencia))

#Cálculo da melting temp
print("Melting Temperature :", mt.Tm_GC(sequencia))



